[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "shared-eu"
version = "0.1.0"
description = "Shared EU utilities and data structures for tax migration"
authors = [
    {name = "BasedGuide", email = "contact@basedguide.com"},
]
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
]

[tool.hatch.build.targets.wheel]
packages = ["shared_eu"]

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "N", "W"]
ignore = ["E501"]

[tool.black]
line-length = 100
