ALL_COUNTRIES = {
    "Afghanistan": "not-included",
    "Albania": "albania",
    "Algeria": "algeria",
    "Andorra": "not-included",
    "Angola": "angola",
    "Antigua and Barbuda": "not-included",
    "Argentina": "argentina",
    "Armenia": "armenia",
    "Australia": "australia",
    "Austria": "austria",
    "Azerbaijan": "azerbaijan",
    "Bahamas": "not-included",
    "Bahrain": "bahrain",
    "Bangladesh": "bangladesh",
    "Barbados": "barbados",
    "Belarus": "not-included",
    "Belgium": "belgium",
    "Belize": "not-included",
    "Benin": "not-included",
    "Bhutan": "not-included",
    "Bolivia": "bolivia",
    "Bosnia and Herzegovina": "bosnia-and-herzegovina",
    "Botswana": "botswana",
    "Brazil": "brazil",
    "Brunei": "not-included",
    "Bulgaria": "bulgaria",
    "Burkina Faso": "not-included",
    "Burundi": "not-included",
    "Côte d'Ivoire": "ivory-coast",
    "Cabo Verde": "cabo-verde",
    "Cambodia": "cambodia",
    "Cameroon": "republic-of-cameroon",
    "Canada": "canada",
    "Central African Republic": "not-included",
    "Chad": "chad",
    "Chile": "chile",
    "China": "peoples-republic-of-china",
    "Colombia": "colombia",
    "Comoros": "not-included",
    "Congo (Congo-Brazzaville)": "republic-of-congo",
    "Costa Rica": "costa-rica",
    "Croatia": "croatia",
    "Cuba": "not-included",
    "Cyprus": "cyprus",
    "Czechia (Czech Republic)": "czech-republic",
    "Denmark": "denmark",
    "Djibouti": "not-included",
    "Dominica": "not-included",
    "Dominican Republic": "dominican-republic",
    "Ecuador": "ecuador",
    "Egypt": "egypt",
    "El Salvador": "el-salvador",
    "Equatorial Guinea": "equatorial-guinea",
    "Eritrea": "not-included",
    "Estonia": "estonia",
    "Eswatini (fmr. Swaziland)": "eswatini",
    "Ethiopia": "ethiopia",
    "Fiji": "not-included",
    "Finland": "finland",
    "France": "france",
    "Gabon": "gabon",
    "Gambia": "not-included",
    "Georgia": "georgia",
    "Germany": "germany",
    "Ghana": "ghana",
    "Greece": "greece",
    "Grenada": "not-included",
    "Guatemala": "guatemala",
    "Guinea": "not-included",
    "Guinea-Bissau": "not-included",
    "Guyana": "guyana",
    "Haiti": "not-included",
    "Honduras": "honduras",
    "Hungary": "hungary",
    "Iceland": "iceland",
    "India": "india",
    "Indonesia": "indonesia",
    "Iran": "not-included",
    "Iraq": "iraq",
    "Ireland": "ireland",
    "Israel": "israel",
    "Italy": "italy",
    "Jamaica": "jamaica",
    "Japan": "japan",
    "Jordan": "jordan",
    "Kazakhstan": "kazakhstan",
    "Kenya": "kenya",
    "Kiribati": "not-included",
    "Kuwait": "kuwait",
    "Kyrgyzstan": "not-included",
    "Laos": "lao-pdr",
    "Latvia": "latvia",
    "Lebanon": "lebanon",
    "Lesotho": "not-included",
    "Liberia": "not-included",
    "Libya": "libya",
    "Liechtenstein": "liechtenstein",
    "Lithuania": "lithuania",
    "Luxembourg": "luxembourg",
    "Madagascar": "madagascar",
    "Malawi": "not-included",
    "Malaysia": "malaysia",
    "Maldives": "not-included",
    "Mali": "not-included",
    "Malta": "malta",
    "Marshall Islands": "not-included",
    "Mauritania": "mauritania",
    "Mauritius": "mauritius",
    "Mexico": "mexico",
    "Micronesia": "not-included",
    "Moldova": "moldova",
    "Monaco": "not-included",
    "Mongolia": "mongolia",
    "Montenegro": "montenegro",
    "Morocco": "morocco",
    "Mozambique": "mozambique",
    "Myanmar (formerly Burma)": "myanmar",
    "Namibia": "republic-of-namibia",
    "Nauru": "not-included",
    "Nepal": "not-included",
    "Netherlands": "netherlands",
    "New Zealand": "new-zealand",
    "Nicaragua": "nicaragua",
    "Niger": "not-included",
    "Nigeria": "nigeria",
    "North Korea": "not-included",
    "North Macedonia": "north-macedonia",
    "Norway": "norway",
    "Oman": "oman",
    "Pakistan": "pakistan",
    "Palau": "not-included",
    "Palestine State": "palestinian-territories",
    "Panama": "panama",
    "Papua New Guinea": "papua-new-guinea",
    "Paraguay": "paraguay",
    "Peru": "peru",
    "Philippines": "philippines",
    "Poland": "poland",
    "Portugal": "portugal",
    "Qatar": "qatar",
    "Romania": "romania",
    "Russia": "not-included",
    "Rwanda": "rwanda",
    "Saint Kitts and Nevis": "not-included",
    "Saint Lucia": "saint-lucia",
    "Saint Vincent and the Grenadines": "not-included",
    "Samoa": "not-included",
    "San Marino": "not-included",
    "Sao Tome and Principe": "not-included",
    "Saudi Arabia": "saudi-arabia",
    "Senegal": "senegal",
    "Serbia": "serbia",
    "Seychelles": "not-included",
    "Sierra Leone": "not-included",
    "Singapore": "singapore",
    "Slovakia": "slovak-republic",
    "Slovenia": "slovenia",
    "Solomon Islands": "not-included",
    "Somalia": "not-included",
    "South Africa": "south-africa",
    "South Korea": "republic-of-korea",
    "South Sudan": "not-included",
    "Spain": "spain",
    "Sri Lanka": "not-included",
    "Sudan": "not-included",
    "Suriname": "not-included",
    "Sweden": "sweden",
    "Switzerland": "switzerland",
    "Syria": "not-included",
    "Tajikistan": "not-included",
    "Tanzania": "tanzania",
    "Thailand": "thailand",
    "Timor-Leste": "timor-leste",
    "Togo": "not-included",
    "Tonga": "not-included",
    "Trinidad and Tobago": "trinidad-and-tobago",
    "Tunisia": "tunisia",
    "Turkey": "turkey",
    "Turkmenistan": "not-included",
    "Tuvalu": "not-included",
    "Uganda": "uganda",
    "Ukraine": "ukraine",
    "United Arab Emirates": "united-arab-emirates",
    "United Kingdom": "united-kingdom",
    "United States of America": "united-states",
    "Uruguay": "uruguay",
    "Uzbekistan": "republic-of-uzbekistan",
    "Vanuatu": "not-included",
    "Vatican City": "not-included",
    "Venezuela": "venezuela",
    "Vietnam": "vietnam",
    "Yemen": "not-included",
    "Zambia": "zambia",
    "Zimbabwe": "not-included"
}