"""add last verification email sent field

Revision ID: 08d0987c9c10
Revises: 0cc8b12932ce
Create Date: 2025-03-10 12:59:28.630775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d0987c9c10'
down_revision: Union[str, None] = '0cc8b12932ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_verification_email_sent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_email_sent')
    # ### end Alembic commands ###
