"""Add climate columns

Revision ID: 9a1634e888ef
Revises: 
Create Date: 2025-02-28 16:23:05.756693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1634e888ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_profiles', sa.Column('avg_temperature', sa.Float(), nullable=True))
    op.add_column('country_profiles', sa.Column('min_temperature', sa.Float(), nullable=True))
    op.add_column('country_profiles', sa.Column('max_temperature', sa.Float(), nullable=True))
    op.add_column('country_profiles', sa.Column('climate_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country_profiles', 'climate_type')
    op.drop_column('country_profiles', 'max_temperature')
    op.drop_column('country_profiles', 'min_temperature')
    op.drop_column('country_profiles', 'avg_temperature')
    # ### end Alembic commands ###
