"""make_nickname_nullable

Revision ID: f54a8f027386
Revises: 9a1634e888ef
Create Date: 2025-03-05 15:39:57.958539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f54a8f027386'
down_revision: Union[str, None] = '9a1634e888ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchases_product_id_fkey', 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sessions', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('sessions_token_key', 'sessions', type_='unique')
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.drop_constraint('user_profiles_user_id_key', 'user_profiles', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('user_profiles_user_id_key', 'user_profiles', ['user_id'])
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.create_unique_constraint('sessions_token_key', 'sessions', ['token'])
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sessions', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key('purchases_product_id_fkey', 'purchases', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
